<?php

return [
    "1" => "Bụi sơn/ Paint dirt (polish)",
    "2" => "Chảy sơn/Paint sag/paint run (polish)",
    "3" => "Bụi sơn/Paint dirt(touchup)",
    "4" => "Chảy sơn/Paint sag/paint run (touchup)",
    "5" => "Lỗ dầu/ Oil hole",
    "6" => "Cặn ED/  Dirt created from ED dipping processing",
    "7" => "Trầy xước sơn/ Paint scratch",
    "9" => "Dính keo sealer/ Sealer stick ",
    "10" => "Da cam/ Orange peel",
    "11" => "Sọc đốm/ Striped line",
    "12" => "Móp, biến dạng/ Dent/deformation",
    "13" => "Nứt, bong tróc sealer/ Crack, peeling sealer",
    "14" => "Thiếu màu/ Thin paint",
    "15" => "Thiếu bóng/ Poor gloss",
    "16" => "Xì sơn/ Blister painting",
    "17" => "Sọc ED/ Stripes ED",
    "18" => "Dấu chà nhám/ Sanding mark",
    "19" => "Đám mây/ Cloudy",
    "20" => "Khác màu/ Not color matching",
    "21" => "Sần sùi bề mặt/ Surface roughness",
    "22" => "Rổ, bong bóng/ Pin hole",
    "23" => "Thiếu vật tư/ Missing parts",
    "24" => "Sửa lỗi không hoàn thiện/ Repair imperfection",
    "25" => "Lột mí sơn dặm/ Peeling paint repair mark",
    "26" => "Lỗi đánh pát/ Polishing mark",
    "27" => "Tàn sơn/ Over spray",
    "28" => "Xước lò xo/ Scratches caused by sanding",
    "29" => "Lỗi tem dán (phồng tem, lệch..)/Black tape defect (air bubble, alignment, missing",
    "30" => "Lỗi khác/ Other",
    "31" => "Xì keo",
    "32" => "Ké màu",
    "33" => "Xì mazda",
    "34" => "Con trùng",
    "35" => "Dấu khuyết ",
    "36" => "Lồi bề mặt"
];