<?php

$configFileCarOld = [
    'SEALER' => [
        "1-Capotrong" => "L16",
        "2-Khoangdongco" => "L17",
        "3-HoctruocRH" => "L18",
        "4-ChongonRH" => "L19",
        "5-MuiRH" => "L20",
        "6-CuatruocRH" => "L21",
        "7-CuasauRH" => "L22",
        "8-HocsauRH" => "L23",
        "9-DensauRH" => "L24",
        "10-HoctruocLH" => "L27",
        "11-ChongonLH" => "L28",
        "12-MuiLH" => "L29",
        "13-CuatruocLH" => "L30",
        "14-Lotsantruoc" => "L31",
        "15-CuasauLH" => "L32",
        "16-Lotsansau" => "L33",
        "17-NapNL" => "L34",
        "18-HocsauLH" => "L35",
        "19-DensauLH" => "L36",
        "20-Ngoaicop" => "L37",
        "21-Trongcop" => "L38",
    ],
    'LH' => [
        "0-Napnl" => "L21",
        "1-Capo" => "L6",
        "2-Trongcapo" => "L6",
        "3-Khoangdongco" => "L6",
        "4-MuiLH" => "L8",
        "5-GomaLH" => "L11",
        "6-CuatruocLH" => "L13",
        "7-NguongtrongLH" => "L17",
        "8-CuasauLH" => "L15",
        "9-ManghongLH" => "L19",
    ],
    'RH' => [
        "1-MuiRH" => "L24",
        "2-Ngoaicop" => "L26",
        "3-Trongcop" => "L26",
        "4-GomaRH" => "L29",
        "5-CuatruocRH" => "L31",
        "6-NguongcuaRH" => "L35",
        "7-CuasauRH" => "L33",
        "8-ManghongRH" => "L37",
    ]
];

$configFileCarNew = [
    'SEALER' => [
        "1-Capotrong" => "L16",
        "2-Khoangdongco" => "L17",
        "3-HoctruocRH" => "L18",
        "4-ChongonRH" => "L19",
        "5-MuiRH" => "L20",
        "6-CuatruocRH" => "L21",
        "7-CuasauRH" => "L22",
        "8-HocsauRH" => "L23",
        "9-DensauRH" => "L24",
        "10-HoctruocLH" => "L27",
        "11-ChongonLH" => "L28",
        "12-MuiLH" => "L29",
        "13-CuatruocLH" => "L30",
        "14-Lotsantruoc" => "L31",
        "15-CuasauLH" => "L32",
        "16-Lotsansau" => "L33",
        "17-NapNL" => "L34",
        "18-HocsauLH" => "L35",
        "19-DensauLH" => "L36",
        "20-Ngoaicop" => "L37",
        "21-Trongcop" => "L38",
    ],
    'LH' => [
        "10-Napnhienlieu" => "L21",
        "1-Capo" => "L6",
        "2-Trongcapo" => "L6",
        "3-Khoangdongco" => "L6",
        "4-MuiLH" => "L8",
        "5-GomaLH" => "L11",
        "6-CuatruocLH" => "L13",
        "7-NguongtrongLH" => "L17",
        "8-CuasauLH" => "L15",
        "9-ManghongLH" => "L19",
    ],
    'RH' => [
        "1-MuiRH" => "L24",
        "2-Cop" => "L26",
        "3-GomaRH" => "L29",
        "4-CuatruocRH" => "L31",
        "5-NguongtrongRH" => "L35",
        "6-CuasauRH" => "L33",
        "7-ManghongRH" => "L37",
    ]
];

$configFileCarGAY = [
    'SEALER' => [
        "1-Capotrong" => "L16",
        "2-Khoangdongco" => "L17",
        "3-HoctruocRH" => "L18",
        "4-ChongonRH" => "L19",
        "5-MuiRH" => "L20",
        "6-CuatruocRHs" => "L21",
        "7-CuasauRH" => "L22",
        "8-HocsauRH" => "L23",
        "9-DensauRH" => "L24",
        "10-HoctruocLH" => "L27",
        "11-ChongonLH" => "L28",
        "12-MuiLH" => "L29",
        "13-CuatruocLH" => "L30",
        "14-Lotsantruoc" => "L31",
        "15-CuasauLH" => "L32",
        "16-Lotsansau" => "L33",
        "17-NapNL" => "L34",
        "18-HocsauLH" => "L35",
        "19-DensauLH" => "L36",
        "20-Ngoaicop" => "L37",
        "21-Trongcop" => "L38",
    ],
    'LH' => [
        "10-napnl" => "L21",
        "1-Capo" => "L6",
        "2-TrongCapo" => "L6",
        "3-Khoangdongco" => "L6",
        "4-MuiLH" => "L8",
        "5-GomaLH" => "L11",
        "6-CuatruocLH" => "L13",
        "7-NguongtrongLH" => "L17",
        "8-CuasauLH" => "L15",
        "9-ManghongLH" => "L19",
    ],
    'RH' => [
        "1-MuiRH" => "L24",
        "2-Ngoaicop" => "L26",
        "3-Nguongtrongcop" => "L26",
        "4-Trongcop"=> "L26",
        "5-GomaRH" => "L29",
        "6-CuatruocRH" => "L31",
        "7NguongtrongRH" => "L35",
        "8-CuasauRH" => "L33",
        "9-ManghongRH" => "L37",
    ]
];

$configExcelSheet1 = [
    'i' => 13,
    'ss' => ['S', 'AE','AM'],
    'now' => 0,
    'count' => 0,
    'height' => 120,
    '_sSum' => 4,
    'userCheckLocation' => 'A41',
    'userCreateLocation' => 'I41',
    'vincodeLocation' => 'A9',
    'colorLocation' => 'Q9',
    'cartypeLocation' => 'V7',
    'dayexportLocation' => 'V9',
    'carfolerLocation' => 'AJ4',
    'signatureSubmit1' => 'O19',
    'signatureSubmit2' => 'O32',
];

$configExcelSheet2 = [
    'i' => 3,
    'ss' => ['S', 'AE','AO'],
    'now' => 0,
    'count' => 0,
    'height' => 110,
    '_sSum' => 5,
    'userPolishLocation' => 'AL43',
    'userRepairLocation' => 'AL44',
    'userRepairV2Location' => 'AU43',
    'vincodeLocation' => '',
    'colorLocation' => '',
    'cartypeLocation' => '',
    'dayexportLocation' => '',
    'carfolerLocation' => '',
    'signatureRH1' => 'O24',
    'signatureRH2' => 'O33',
    'signatureLH1' => 'O6',
    'signatureLH2' => 'O15',
];